import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
export async function verifyJourneys(browser,origin,output){
 const ctx=await browser.newContext({viewport:{width:1440,height:900}});
 // Static source clients may capture fetch during import; keep those reads local too.
 await ctx.route('**/ux-fixture/api/**',route=>route.fulfill({json:{ok:true,statusCode:200,value:route.request().url().endsWith('/lan/runtime')?{enabled:false,endpoints:[],warnings:[],frontendPort:3107,backendPort:3107,allowedOriginsSource:'none'}:[]}}));
 const page=await ctx.newPage();page.setDefaultTimeout(10000);
 const checks=[],errors=[],screenshots=[];
 page.on('pageerror',e=>errors.push(e.message));
 const check=(name,value)=>{assert.ok(value,name);checks.push(name);};
 const go=extra=>page.goto(origin+'/tests/live-play/?journey&'+extra+'&apiBase='+encodeURIComponent(origin+'/ux-fixture'));
 const shot=async name=>{await page.screenshot({path:output+'/'+name+'.png',animations:'disabled'});screenshots.push(name+'.png');};
 const creator=()=>page.locator('[data-canonical-creator="dnd"]');
 const sheet=()=>page.locator('[data-canonical-surface="campaign-actor-sheet"]');
 const join=async()=>{await page.getByPlaceholder('ABC123').fill('MOON12');await page.getByRole('button',{name:'加入大厅',exact:true}).click();await page.getByText('选择入场角色',{exact:true}).waitFor();};
 const submit=async()=>{await page.getByRole('button',{name:'提交角色申请',exact:true}).click();await page.getByText('等待主持人审核',{exact:true}).waitFor();};
 await fs.mkdir(output,{recursive:true});
 await go('journey-join&existing');await join();
 check('invite join preserves server member role',await page.evaluate(()=>window.journeyFixture.writes[0].body.requestedRole==='player'));
 check('temporary entry is absent from primary actions',await page.locator('[data-character-primary-actions]').getByRole('button',{name:'使用临时角色'}).count()===0);
 check('temporary option is collapsed',!await page.getByRole('button',{name:'使用临时角色',exact:true}).isVisible());
 const picker=page.getByRole('combobox').filter({has:page.locator('option[value="local:existing-hero"]')});
 await picker.selectOption('local:existing-hero');await submit();
 check('existing character sync uses canonical Vault',await page.evaluate(()=>window.journeyFixture.writes.some(w=>w.kind==='vault.create'&&w.body.localActorId==='existing-hero')));
 check('admission receives cloud identity not browser id',await page.evaluate(()=>window.journeyFixture.writes.find(w=>w.kind==='binding.submit').body.actorRef.actorId==='cloud-0'));
 check('approval remains required before readiness',await page.getByRole('button',{name:'我已准备',exact:true}).count()===0);
 await page.evaluate(()=>window.journeyFixture.approve());await page.getByRole('button',{name:'我已准备',exact:true}).click();await page.getByRole('button',{name:'进入跑团桌面',exact:true}).click();await page.locator('[data-live-play="player"]').waitFor();
 check('existing player reaches table after approval and readiness',true);
 await go('journey-join');await join();await shot('new-player-empty');
 check('empty library promotes canonical creation',await page.getByRole('button',{name:'创建角色',exact:true}).isVisible());
 check('no manual stats or identifier in ordinary join',!await page.getByText('当前 HP',{exact:true}).isVisible()&&await page.getByText('角色 ID（可选）',{exact:true}).count()===0);
 await page.getByRole('button',{name:'创建角色',exact:true}).click();
 check('room opens existing DND Creator',await creator().getByText('角色创建器',{exact:true}).isVisible());
 await creator().getByRole('textbox',{name:'角色名称 *',exact:true}).fill('未完成的旅人');
 await creator().getByRole('button',{name:'返回大厅，稍后继续',exact:true}).click();
 check('creator cancellation restores focus to its entry',await page.getByRole('button',{name:'创建角色',exact:true}).evaluate(e=>e===document.activeElement));
 await page.getByRole('button',{name:'创建角色',exact:true}).click();
 check('cancel and reopen preserve unfinished character draft',await creator().getByRole('textbox',{name:'角色名称 *',exact:true}).inputValue()==='未完成的旅人');
 check('cancel does not submit or create cloud actor',await page.evaluate(()=>window.journeyFixture.writes.every(w=>w.kind==='join')));
 await page.evaluate(()=>window.journeyFixture.fillReady());await shot('canonical-dnd-creator');
 await creator().getByRole('button',{name:'完成创建',exact:true}).click();await creator().waitFor({state:'hidden'});
 check('completion saves through canonical store',await page.evaluate(()=>window.journeyFixture.character().isCompleted===true));
 check('completion automatically selects returned identity',await page.getByRole('combobox').filter({has:page.locator('option[value="local:journey-draft"]')}).inputValue()==='local:journey-draft');
 check('completion has not silently submitted admission',await page.evaluate(()=>!window.journeyFixture.writes.some(w=>w.kind==='binding.submit')));
 await shot('created-character-return');await submit();await page.evaluate(()=>window.journeyFixture.approve());await page.getByRole('button',{name:'我已准备',exact:true}).click();await page.getByRole('button',{name:'进入跑团桌面',exact:true}).click();await page.locator('[data-live-play="player"]').waitFor();check('newly created character can complete join',true);
 await go('lobby&role=host');await shot('host-only');
 check('host enters without character form',await page.getByRole('button',{name:'以主持人身份进入桌面',exact:true}).isEnabled()&&!await page.getByRole('button',{name:'创建角色',exact:true}).isVisible());
 await page.getByRole('button',{name:'以主持人身份进入桌面',exact:true}).click();await page.locator('[data-live-play="host"]').waitFor();check('host-only reaches live table',true);
 await go('lobby&role=host&existing');await page.getByText('我也扮演角色（可选）',{exact:true}).click();await page.getByRole('combobox').filter({has:page.locator('option[value="local:existing-hero"]')}).selectOption('local:existing-hero');
 check('GM-PC uses ordinary character flow',await page.getByRole('button',{name:'提交角色申请',exact:true}).isVisible()&&await page.getByRole('button',{name:'创建主持人角色'}).count()===0);
 await page.getByRole('button',{name:'提交角色申请',exact:true}).click();await page.waitForFunction(()=>window.journeyFixture.writes.some(w=>w.kind==='binding.submit'));
 check('GM-PC keeps host membership and existing submission',await page.evaluate(()=>window.journeyFixture.writes.find(w=>w.kind==='binding.submit').body.memberId==='host'));
 await go('lobby&role=player');await page.getByText('更多加入方式',{exact:true}).click();await page.getByRole('button',{name:'使用临时角色',exact:true}).click();
 check('temporary scope and lack of automatic conversion are explicit',await page.getByText(/目前不能自动转为角色库角色/).isVisible());
 check('temporary stats stay advanced',!await page.getByText('当前 HP',{exact:true}).isVisible());
 await page.getByRole('textbox',{name:'角色名',exact:true}).fill('今晚的旅人');await shot('temporary-explicit');await submit();
 check('temporary submission creates no Vault identity',await page.evaluate(()=>{const w=window.journeyFixture.writes;return !w.some(x=>x.kind==='vault.create')&&w.find(x=>x.kind==='binding.submit').body.actorRef.source==='quickDraft'&&!w.find(x=>x.kind==='binding.submit').body.actorRef.actorId;}));
 await go('journey-join');await page.getByPlaceholder('ABC123').fill('MOON12');await page.getByRole('button',{name:'以旁观者加入',exact:true}).click();await page.getByRole('button',{name:'进入跑团桌面',exact:true}).click();await page.locator('[data-live-play="spectator"]').waitFor();check('spectator bypasses character flow without permission changes',true);
 await go('ia&workspace&role=host');check('manual room records are demoted',!await page.getByRole('button',{name:'创建房间记录',exact:true}).isVisible());await page.getByText('战役准备与角色管理',{exact:true}).click();await shot('campaign-cast');await page.locator('[data-cast-group=monster]').scrollIntoViewIfNeeded();await shot('campaign-cast-groups');
 check('cast tasks replace default type dropdown',await page.getByRole('combobox',{name:'角色类型'}).count()===0&&await page.getByRole('button',{name:'添加玩家角色',exact:true}).isVisible());
 check('cast groups reflect player NPC monster jobs',await page.locator('[data-cast-group]').count()===3);
 check('AI is no longer the primary preparation block',!await page.getByText('成果仅你可见',{exact:true}).isVisible());
 await page.getByRole('button',{name:'添加玩家角色',exact:true}).click();check('player cast leads to owner character admission not blank actor CRUD',await page.locator('[data-player-cast-guidance]').isVisible()&&!await page.getByPlaceholder('角色名称',{exact:true}).isVisible());await page.keyboard.press('Escape');await page.locator('[role=dialog]').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'创建 NPC',exact:true}).click();await sheet().getByPlaceholder('显示名称').fill('守桥人');check('NPC is not persisted before canonical create',await page.evaluate(()=>window.iaFixture.actors.every(a=>a.displayName!=='守桥人')));await sheet().getByRole('button',{name:'创建角色',exact:true}).click();await sheet().waitFor();
 check('NPC intent creates canonical NPC and opens shared sheet',await page.evaluate(()=>window.iaFixture.actors.at(-1).actorKind==='npc')&&await sheet().getByPlaceholder('显示名称').inputValue()==='守桥人');await page.keyboard.press('Escape');await page.locator('[role=dialog]').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'添加怪物',exact:true}).first().click();await page.getByRole('button',{name:/资料库地精/}).click();
 check('monster catalog opens with template editing demoted',await page.getByRole('button',{name:'加入战役并打开角色',exact:true}).isVisible()&&!await page.getByRole('button',{name:'保存基础资料',exact:true}).isVisible());
 await shot('monster-catalog');await page.getByRole('button',{name:'加入战役并打开角色',exact:true}).click();await sheet().waitFor();
 check('catalog selection preserves template linkage and opens canonical actor',await page.evaluate(()=>window.iaFixture.actors.at(-1).sourceActorId==='private-monster:catalog-goblin')&&await sheet().getByPlaceholder('显示名称').inputValue()==='资料库地精');await page.keyboard.press('Escape');await page.locator('[role=dialog]').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'恢复联机大厅',exact:true}).click();await page.getByRole('button',{name:'以主持人身份进入桌面',exact:true}).click();await page.getByRole('button',{name:'准备 / 管理',exact:true}).click();await page.locator('.live-context-panel').getByRole('button',{name:'打开战役战斗卡',exact:true}).click();await page.getByRole('button',{name:'创建 NPC',exact:true}).click();await sheet().getByPlaceholder('显示名称').fill('临场商人');await sheet().getByRole('button',{name:'创建角色',exact:true}).click();await sheet().waitFor();
 check('live improvisation retains table while reusing canonical campaign creation',await page.locator('[data-live-play="host"]').count()===1&&await sheet().getByPlaceholder('显示名称').inputValue()==='临场商人');await page.keyboard.press('Escape');await page.locator('[role=dialog]').waitFor({state:'hidden'});await page.locator('[data-live-play="host"]').waitFor();check('improvisation returns to same live table',await page.locator('[data-live-play="host"]').isVisible());
 await page.setViewportSize({width:1024,height:768});await go('lobby&role=player');await shot('player-lobby-1024');check('lobby has no horizontal overflow at tablet width',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await go('lobby&role=player&existing');await page.getByRole('button',{name:'创建角色',exact:true}).click();check('creating from completed character starts a separate draft',await page.evaluate(()=>window.journeyFixture.character().id!=='existing-hero'));check('existing completed character remains in Vault',await page.evaluate(()=>window.journeyFixture.savedCharacters().some(c=>c.id==='existing-hero'&&c.isCompleted)));await creator().waitFor();check('canonical creator fits tablet viewport',await creator().evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;}));
 await go('ia&workspace&role=host&custom');await page.getByText('战役准备与角色管理',{exact:true}).click();await page.getByRole('button',{name:'创建 NPC',exact:true}).click();check('custom system creation has no DND editor',await sheet().count()===0);await page.getByPlaceholder('角色名称',{exact:true}).fill('通用人物');await page.getByRole('button',{name:'创建战役角色',exact:true}).click();await page.locator('[role=dialog]').waitFor({state:'hidden'});check('custom system retains existing campaign record semantics',await page.evaluate(()=>window.iaFixture.actors.at(-1).actorKind==='npc')&&await sheet().count()===0);
 check('no browser exceptions',errors.length===0);
 const result={passed:checks.length,checks,errors,screenshots};await fs.writeFile(output+'/browser-results.json',JSON.stringify(result,null,2));await ctx.close();return result;
}
