import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
/** Runs against the actual bridge and components with a development-only transport fixture. */
export async function verifyLivePlay(browser, origin, output) {
 await mkdir(output,{recursive:true});
 const context=await browser.newContext({viewport:{width:1440,height:900}});
 const page=await context.newPage(), errors=[], checks=[], shots=[], measurements=[];
 page.on('pageerror',error=>errors.push(error.message));
 const check=(name,condition)=>{assert.ok(condition,name);checks.push(name);};
 const goto=async(query)=>{await page.goto(origin+'/tests/live-play/index.html?'+query);await page.locator('[data-live-play]').waitFor();await page.waitForFunction(()=>document.querySelector('.live-connection')?.textContent?.includes('实时同步'));};
 const shot=async(name)=>{await page.screenshot({path:output+'/'+name+'.png'});shots.push(name+'.png');};
 const geometry=async(name)=>{const value=await page.evaluate(()=>{const r=document.querySelector('.live-tabletop').getBoundingClientRect();return {width:innerWidth,height:innerHeight,tableWidth:r.width,tableHeight:r.height,tableFraction:r.width*r.height/(innerWidth*innerHeight),overflow:document.documentElement.scrollWidth>innerWidth,bodyScroll:document.documentElement.scrollHeight>innerHeight};});check(name+' has no page overflow',!value.overflow&&!value.bodyScroll);measurements.push({name,...value});};
 const attack=()=>page.locator('[data-live-attack]');
 await goto('role=player');
 await page.getByRole('combobox',{name:'攻击动作'}).selectOption('longbow');
 check('supporting panels start collapsed',await page.locator('.live-context-panel').isHidden());
 check('own projected vitals visible', (await attack().innerText()).includes('HP 24/28'));
 check('six combatants shown',await page.locator('.live-initiative button').count()===6);
 check('attack waits for target',await page.getByRole('button',{name:'攻击',exact:true}).isDisabled());
 await geometry('player combat 1440x900');await shot('player-combat-1440');
 await page.locator('[data-map-token="t3"]').click();
 check('target click does not report a movement error',!await page.getByText('主持人尚未授权你移动角色，或该 Token 不属于你的已准入角色。',{exact:true}).isVisible());
 check('map selects attack target',await page.getByRole('combobox',{name:'攻击目标'}).inputValue()==='c3');
 await page.getByRole('combobox',{name:'掷骰方式'}).selectOption('advantage');
 await page.getByRole('button',{name:'攻击',exact:true}).click();
 await attack().getByText('命中 · 23',{exact:true}).waitFor();
 const intent=await page.evaluate(()=>window.uxFixture.intents[0]);
 check('attack submits original intent fields only',JSON.stringify(Object.keys(intent).sort())===JSON.stringify(['memberId','intentId','actorCombatantId','targetCombatantId','actionId','mode'].sort()));
 check('attack carries selected actor target mode',intent.actorCombatantId==='c0'&&intent.targetCombatantId==='c3'&&intent.mode==='advantage');
 check('six combatants remain after projected resolution',await page.locator('.live-initiative button').count()===6);
 check('projected resulting HP appears inline',(await attack().innerText()).includes('HP 13'));
 const activity=page.getByRole('button',{name:/聊天.*动态/});
 await activity.click();
 check('side panel opening focuses close',await page.evaluate(()=>document.activeElement?.hasAttribute('data-panel-close')));
 check('raw events absent in ordinary activity',!await page.locator('.live-context-panel pre').isVisible().catch(()=>false));
 await shot('player-result-activity-1440');
 await page.getByRole('button',{name:'聊天',exact:true}).click();
 const chat=page.getByRole('textbox',{name:'公开聊天消息'});
 await chat.fill('守住桥头');
 await page.keyboard.press('Escape');
 check('Escape returns focus to panel trigger',await activity.evaluate(el=>el===document.activeElement));
 await activity.click();
 check('chat draft survives collapse',await chat.inputValue()==='守住桥头');
 await page.getByRole('button',{name:'发送',exact:true}).click();
 await page.getByRole('log',{name:'聊天消息'}).getByText('守住桥头',{exact:true}).waitFor();
 check('HTTP and socket chat echoes deduplicate',await page.getByRole('log',{name:'聊天消息'}).getByText('守住桥头',{exact:true}).count()===1);
 check('chat hides combat events',!(await page.getByRole('log',{name:'聊天消息'}).innerText()).includes('攻击结算'));
 await page.getByRole('button',{name:'角色卡',exact:true}).click();
 check('single supporting panel',await page.locator('.live-context-content:visible').count()===1);
 check('sheet contains projected HP',(await page.locator('.live-context-panel').innerText()).replaceAll(' ', '').includes('24/28'));
 await shot('player-character-1440');
 await page.keyboard.press('Escape');
 await page.locator('[data-map-token="t3"]').focus();await page.keyboard.press('Shift+Enter');
 await page.getByRole('dialog').waitFor();
 check('keyboard opens token information',await page.getByRole('dialog').isVisible());
 await page.keyboard.press('Shift+Tab');
 check('modal wraps focus',await page.getByRole('dialog').evaluate(el=>el.contains(document.activeElement)));
 await page.keyboard.press('Escape');check('modal Escape restores token focus',await page.locator('[data-map-token="t3"]').evaluate(el=>el===document.activeElement));
 const targetBox=await page.locator('[data-map-token="t3"]').boundingBox();
 await page.mouse.move(targetBox.x+targetBox.width/2,targetBox.y+targetBox.height/2);await page.mouse.down();await page.mouse.move(targetBox.x+targetBox.width/2+30,targetBox.y+targetBox.height/2+20,{steps:4});await page.mouse.up();
 check('unauthorized drag still reports denial',await page.getByText('主持人尚未授权你移动角色，或该 Token 不属于你的已准入角色。',{exact:true}).isVisible());
 await goto('role=player&retry');
 await page.getByRole('combobox',{name:'攻击动作'}).selectOption('longbow');
 await page.getByRole('combobox',{name:'攻击目标'}).selectOption('c3');
 await page.getByRole('button',{name:'攻击',exact:true}).click();
 await attack().getByRole('alert').waitFor();
 await page.locator('[data-map-token="t4"]').click();
 check('pending intent keeps its displayed target despite map selection',await page.getByRole('combobox',{name:'攻击目标'}).inputValue()==='c3');
 check('pending target is frozen',await page.getByRole('combobox',{name:'攻击目标'}).isDisabled());
 await page.getByRole('button',{name:'队伍 5',exact:true}).click();await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'重试同一攻击',exact:true}).click();
 await attack().getByText('已恢复原始结果。',{exact:true}).waitFor();
 const retries=await page.evaluate(()=>window.uxFixture.intents);
 check('retry preserves byte-equivalent intent',retries.length===2&&JSON.stringify(retries[0])===JSON.stringify(retries[1]));
 check('retry has one resolution event',await page.evaluate(()=>window.uxFixture.events.filter(e=>e.kind==='combat.attack_resolved').length)===1);
 await page.setViewportSize({width:1920,height:1080});await goto('role=host');
 await page.getByRole('combobox',{name:'控制角色 / NPC'}).selectOption('c3');
 await page.getByRole('combobox',{name:'攻击动作'}).selectOption('longbow');
 await page.getByRole('combobox',{name:'攻击目标'}).selectOption('c0');
 await geometry('host combat 1920x1080');await shot('host-combat-1920');
 await page.getByRole('button',{name:'攻击',exact:true}).click();await attack().getByText('命中 · 23',{exact:true}).waitFor();
 check('host submits selected NPC actor',await page.evaluate(()=>window.uxFixture.intents[0].actorCombatantId)==='c3');
 await page.getByRole('button',{name:'下一回合 →',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.live-initiative button[aria-current=true]')?.textContent?.includes('索恩'));
 check('turn updates with closed inspector',true);
 await page.setViewportSize({width:1024,height:768});await goto('role=host');
 await page.getByRole('button',{name:'战斗 / 裁定',exact:true}).click();
 await geometry('host inspector 1024x768');await shot('host-combat-inspector-1024');
 check('all six combatant rows present',await page.locator('.live-context-panel').getByRole('button',{name:/先攻 [0-9]+/}).count()===6);
 await page.getByRole('button',{name:'网格',exact:true}).click();
 check('map tools close supporting panel',await page.locator('.live-context-panel').isHidden());
 await page.getByRole('button',{name:'准备 / 管理',exact:true}).click();
 check('supporting panel closes map tools',await page.getByText('每格英尺',{exact:true}).isHidden());
 await page.setViewportSize({width:1440,height:900});await goto('role=host&exploration');
 check('exploration has no initiative strip',await page.locator('.live-turn-strip').count()===0);
 check('exploration has no disabled attack form',await page.locator('.live-action-form').count()===0);
 await geometry('host exploration 1440x900');await shot('host-exploration-1440');
 await page.getByRole('button',{name:'返回房间大厅',exact:true}).click();
 await page.getByRole('button',{name:'进入跑团桌面',exact:true}).waitFor();
 check('host character is optional and collapsed',await page.getByText('主持人角色（可选）',{exact:true}).evaluate(el=>!el.parentElement.open));
 check('empty review queue not shown',await page.getByText('主持人待处理',{exact:true}).count()===0);
 await shot('host-lobby-1440');
 await page.getByRole('button',{name:'进入跑团桌面',exact:true}).click();await page.locator('[data-live-play]').waitFor();
 await goto('role=spectator');
 check('spectator has no attack or host management controls',await page.locator('[data-live-attack]').count()===0&&await page.getByRole('button',{name:'准备 / 管理',exact:true}).count()===0);
 await shot('spectator-1440');
 await goto('role=host&custom&exploration');await shot('custom-exploration-1440');
 await page.setViewportSize({width:390,height:844});await goto('role=player');
 await geometry('player narrow fallback 390x844');await shot('player-fallback-390');
 check('primary attack control stays onscreen',await page.getByRole('button',{name:'攻击',exact:true}).evaluate(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight;}));
 await page.setViewportSize({width:1440,height:900});
 await page.goto(origin+'/tests/live-play/index.html?workspace');
 await page.getByRole('button',{name:'恢复联机大厅',exact:true}).waitFor();
 check('campaign creation initially collapsed',await page.getByText('创建战役',{exact:true}).evaluate(el=>!el.parentElement.open));
 check('campaign preparation initially collapsed',await page.getByText('战役准备与角色管理',{exact:true}).evaluate(el=>!el.parentElement.open));
 check('room management initially collapsed',await page.getByText('房间资料与会话管理',{exact:true}).evaluate(el=>!el.parentElement.open));
 check('resume is visible without scrolling',await page.getByRole('button',{name:'恢复联机大厅',exact:true}).evaluate(el=>el.getBoundingClientRect().bottom<innerHeight));
 await shot('campaign-entry-1440');
 check('no browser exceptions',errors.length===0);
 const result={checks,passed:checks.length,errors,screenshots:shots,measurements};
 await writeFile(output+'/browser-results.json',JSON.stringify(result,null,2));
 await context.close();return result;
}
