import type { DndActionDefinition } from './action-registry-types';

export const DND_ACTION_REGISTRY: DndActionDefinition[] = [
  {
    id: 'barbarian_rage_activate_v0',
    name: '激活狂暴 / Rage',
    sourceFeature: '狂暴',
    category: 'classFeature',
    actionType: 'Bonus Action',
    description: '进入狂暴状态的最小动作描述。',
    resourceCost: [{ resourceType: 'classResource', resourceId: 'barbarian_rage', amount: 1 }],
    tags: ['barbarian', 'classResource'],
    notes: 'v0 只消耗 1 次 Rage，不处理持续时间、伤害加值、抗性或提前结束。',
  },
  {
    id: 'bard_bardic_inspiration_grant_v0',
    name: '授予诗人激励 / Bardic Inspiration',
    sourceFeature: '诗人激励',
    category: 'classFeature',
    actionType: 'Bonus Action',
    description: '给予一个目标诗人激励的最小动作描述。',
    resourceCost: [{ resourceType: 'classResource', resourceId: 'bard_bardic_inspiration', amount: 1 }],
    tags: ['bard', 'classResource'],
    notes: 'v0 不选择目标，也不处理反应触发或激励骰使用。',
  },
  {
    id: 'fighter_action_surge_v0',
    name: '动作如潮 / Action Surge',
    sourceFeature: '动作如潮',
    category: 'combat',
    actionType: 'No Action',
    description: '获得额外行动的最小动作描述。',
    resourceCost: [{ resourceType: 'classResource', resourceId: 'fighter_action_surge', amount: 1 }],
    tags: ['fighter', 'classResource'],
    notes: 'v0 只消耗资源，不增加实际行动次数或回合状态。',
  },
  {
    id: 'fighter_second_wind_v0',
    name: '回气 / Second Wind',
    sourceFeature: '回气',
    category: 'classFeature',
    actionType: 'Bonus Action',
    description: '使用回气的最小动作描述。',
    resourceCost: [{ resourceType: 'classResource', resourceId: 'fighter_second_wind', amount: 1 }],
    tags: ['fighter', 'classResource'],
    notes: 'v0 只消耗资源，不掷治疗骰，也不自动恢复生命值。',
  },
  {
    id: 'monk_focus_point_spend_v0',
    name: '消耗专注点 / Focus Point',
    sourceFeature: '专注点',
    category: 'classFeature',
    actionType: 'Special',
    description: '通用消耗 1 点专注点的最小动作描述。',
    resourceCost: [{ resourceType: 'classResource', resourceId: 'monk_focus_points', amount: 1 }],
    tags: ['monk', 'classResource'],
    notes: 'v0 不区分具体武僧招式、动作类型或效果。',
  },
  {
    id: 'paladin_lay_on_hands_spend_v0',
    name: '圣疗池点数 / Lay on Hands',
    sourceFeature: '圣疗池',
    category: 'classFeature',
    actionType: 'Action',
    description: '通用消耗 1 点圣疗池的最小动作描述。',
    resourceCost: [{ resourceType: 'classResource', resourceId: 'paladin_lay_on_hands', amount: 1 }],
    tags: ['paladin', 'classResource'],
    notes: '这是点数型资源；v0 每次只扣 1 点，不选择治疗量、目标或状态移除。',
  },
  {
    id: 'druid_wild_shape_v0',
    name: '荒野形态 / Wild Shape',
    sourceFeature: '荒野形态',
    category: 'classFeature',
    actionType: 'Bonus Action',
    description: '使用荒野形态的最小动作描述。',
    resourceCost: [{ resourceType: 'classResource', resourceId: 'druid_wild_shape', amount: 1 }],
    tags: ['druid', 'classResource'],
    notes: 'v0 只消耗资源，不处理形态选择、属性替换、临时生命值或持续时间。',
  },
  {
    id: 'pact_magic_spend_v0',
    name: '契约魔法位 / Pact Magic',
    sourceFeature: '契约魔法',
    category: 'spellcasting',
    actionType: 'Action',
    description: '通用消耗 1 个契约魔法位的最小动作描述。',
    resourceCost: [{ resourceType: 'pactMagic', amount: 1 }],
    tags: ['warlock', 'pactMagic'],
    notes: 'v0 只消耗 Pact Magic，不处理施法细节、目标、环位选择或标准法术位混用。',
  },
];
