import assert from 'node:assert/strict';
import { migrateCharacter } from '../characterMigration';
import { SPELL_DATA } from '../../data/spells';
import { changeDndSpellbook, getDndSpellManagement } from './spellManagement';

const character = migrateCharacter({ name: 'Spell test', jobClass: '法师', level: 1 });
let model = getDndSpellManagement(character, SPELL_DATA);
assert.ok(model.selectable.length > 0);
assert.ok(model.selectable.every(s => s.level <= 1 && s.classes.includes('法师')));
const spell = model.selectable.find(s => s.level === 1)!; assert.ok(spell);
assert.throws(() => changeDndSpellbook(character, model.selectable, 'prepare', spell), /先加入/);
character.spellbook = changeDndSpellbook(character, model.selectable, 'learn', spell);
character.spellbook = changeDndSpellbook(character, model.selectable, 'prepare', spell);
assert.equal(character.spellbook.prepared.includes(spell.name_cn), true);
character.spellbook = changeDndSpellbook(character, model.selectable, 'learn', spell);
assert.equal(character.spellbook.prepared.length, 0, 'forgetting removes preparation');
const personal = { ...spell, id: 'personal.test', name_cn: 'Personal test', name_en: 'Personal test', classes: [] };
model = getDndSpellManagement(character, SPELL_DATA, [personal]);
character.spellbook = changeDndSpellbook(character, model.selectable, 'learn', personal);
assert.equal(character.spellbook.known.at(-1)?.id, 'personal.test');
const cap = model.preparation.preparedSpellLimit!;
const copies = Array.from({ length: cap + 1 }, (_, i) => ({ ...personal, name_cn: `P${i}` }));
character.spellbook.known = copies; character.spellbook.prepared = copies.slice(0, cap).map(s => s.name_cn);
assert.throws(() => changeDndSpellbook(character, copies, 'prepare', copies.at(-1)!), /最多准备/);
const beforeSlots = JSON.stringify(character.spellbook.slots);
character.spellbook = changeDndSpellbook(character, [], 'learn', copies[0]);
assert.equal(character.spellbook.known.length, cap, 'old source choices can be removed');
assert.equal(JSON.stringify(character.spellbook.slots), beforeSlots, 'management never spends slots');
const warlock = migrateCharacter({ name: 'Pact test', jobClass: '邪术师', level: 3 });
const pact = getDndSpellManagement(warlock, SPELL_DATA);
assert.ok(pact.preparation.pactMagic); assert.ok(pact.selectable.some(s => s.level > 0));
console.log('Spell management smoke passed: shared source/class/level filter, learned prerequisite, preparation cap, personal spells, forget cleanup, legacy removal and pact availability.');
