import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
export async function verifyProductIa(browser, origin, output) {
 const ctx=await browser.newContext({viewport:{width:1440,height:900}});
 const page=await ctx.newPage();page.setDefaultTimeout(8000);
 const checks=[],screenshots=[],errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const check=(name,value)=>{assert.ok(value,name);checks.push(name);};
 const go=async(extra='workspace&role=host')=>page.goto(origin+'/tests/live-play/?ia&'+extra+'&apiBase='+encodeURIComponent(origin+'/ux-fixture'));
 const sheet=()=>page.locator('[data-canonical-surface="campaign-actor-sheet"]');
 const signature=()=>sheet().evaluate(el=>({headings:[...el.querySelectorAll('h4,h5')].map(e=>e.textContent),fields:[...el.querySelectorAll('input')].map(e=>e.getAttribute('placeholder')),buttons:[...el.querySelectorAll('button')].map(e=>e.textContent)}));
 const shot=async name=>{await page.screenshot({path:output+'/'+name+'.png',animations:'disabled'});screenshots.push(name+'.png');};
 const prep=async()=>page.getByText('战役准备与角色管理',{exact:true}).click();
 const openActor=async(index=0)=>page.getByRole('button',{name:'打开战役战斗卡',exact:true}).nth(index+1).click();
 const close=async()=>{await page.keyboard.press('Escape');await sheet().waitFor({state:'hidden'});};
 const live=async()=>{await page.getByRole('button',{name:'恢复联机大厅',exact:true}).click();await page.getByRole('button',{name:'以主持人身份进入桌面',exact:true}).click();await page.locator('[data-map-token="t3"]').waitFor();};
 await fs.mkdir(output,{recursive:true});
 await go();await prep();await openActor(3);
 check('campaign row selects its canonical actor',await sheet().getByPlaceholder('显示名称').inputValue()==='地精斥候');
 const canonical=await signature();
 await sheet().getByPlaceholder('护甲等级',{exact:true}).fill('19');await page.getByRole('button',{name:'保存角色卡',exact:true}).click();
 await page.getByText('角色卡已保存到当前战役。',{exact:true}).waitFor();
 check('save uses existing campaign actor PATCH shape',await page.evaluate(()=>{const w=window.iaFixture.writes.at(-1);return w.id==='actor3'&&w.kind==='actor.update'&&Object.keys(w.input).join()==='overridePayload';}));
 await close();await openActor(3);
 check('reopen reads accepted saved value',await sheet().getByPlaceholder('护甲等级',{exact:true}).inputValue()==='19');
 await page.evaluate(()=>window.iaFixture.failSave=true);
 await sheet().getByPlaceholder('护甲等级',{exact:true}).fill('20');await page.getByRole('button',{name:'保存角色卡',exact:true}).click();
 await page.getByText('角色卡暂时无法保存，请稍后重试。',{exact:true}).waitFor();
 await page.evaluate(()=>window.iaFixture.failSave=false);await close();await openActor(3);
 check('failed save does not become saved truth',await sheet().getByPlaceholder('护甲等级',{exact:true}).inputValue()==='19');
 await page.evaluate(()=>window.iaFixture.holdNextRead=true);await page.getByRole('button',{name:'刷新角色资料',exact:true}).click();
 await page.waitForFunction(()=>!!window.iaFixture.releaseRead);
 await sheet().getByPlaceholder('护甲等级',{exact:true}).fill('21');await page.getByRole('button',{name:'保存角色卡',exact:true}).click();
 await page.getByText('角色卡已保存到当前战役。',{exact:true}).waitFor();await page.evaluate(()=>window.iaFixture.releaseRead());await close();await openActor(3);
 check('older read cannot overwrite accepted save',await sheet().getByPlaceholder('护甲等级',{exact:true}).inputValue()==='21');
 await page.getByRole('button',{name:'清除战役覆写',exact:true}).click();await page.getByText('已清除本战役的角色卡覆写。',{exact:true}).waitFor();await close();await openActor(3);
 check('clear cannot resurrect cached override',await sheet().getByPlaceholder('护甲等级',{exact:true}).inputValue()==='');
 await sheet().getByPlaceholder('护甲等级',{exact:true}).fill('17');await page.getByRole('button',{name:'保存角色卡',exact:true}).click();await page.getByText('角色卡已保存到当前战役。',{exact:true}).waitFor();
 await page.evaluate(()=>window.iaFixture.setServerAc('actor3',18));await page.getByRole('button',{name:'刷新角色资料',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('[placeholder="护甲等级"]')?.value==='18');
 check('refresh reads latest canonical server actor',true);
 await shot('campaign-canonical-editor-1440');await close();
 await page.getByText('房间资料与会话管理',{exact:true}).click();
 check('live-owned session offers no legacy combat editor',await page.getByText('本会话由联机房间管理。请从上方恢复大厅，调整地图或战斗。',{exact:true}).isVisible()&&await page.getByText('会话工具',{exact:true}).count()===0);
 await live();await page.locator('[data-map-token="t3"]').focus();await page.keyboard.press('Shift+Enter');await page.getByRole('button',{name:'打开战役战斗卡',exact:true}).click();
 check('token opens same campaign actor id',await sheet().getByPlaceholder('显示名称').inputValue()==='地精斥候');
 check('token retains accepted state',await sheet().getByPlaceholder('护甲等级',{exact:true}).inputValue()==='18');
 // Clearing removed the attack; compare stable field groups, not action-row count.
 check('token uses canonical heading structure',JSON.stringify((await signature()).headings)===JSON.stringify(canonical.headings));
 check('token passes explicit entry context',await page.locator('[data-entry-source="token"]').isVisible());
 check('live table stays mounted under editor',await page.locator('[data-live-play="host"]').count()===1);
 await shot('token-canonical-editor-1440');
 check('canonical modal settles opaque',await page.locator('[data-entry-source]').evaluate(e=>getComputedStyle(e).opacity==='1'));
 await page.keyboard.press('Tab');check('keyboard stays inside canonical modal',await page.locator('[data-entry-source]').evaluate(e=>e.contains(document.activeElement)));
 await close();await page.waitForFunction(()=>document.activeElement?.textContent==='打开战役战斗卡');check('closing actor returns focus to token entry',await page.getByRole('button',{name:'打开战役战斗卡',exact:true}).evaluate(e=>e===document.activeElement));await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'战斗 / 裁定',exact:true}).click();await page.locator('.live-context-panel').getByRole('button',{name:'打开战役战斗卡',exact:true}).nth(3).click();
 check('combat opens the same actor and surface',await sheet().getByPlaceholder('显示名称').inputValue()==='地精斥候'&&await page.locator('[data-entry-source="combat"]').isVisible());
 await close();await page.getByRole('button',{name:'准备 / 管理',exact:true}).click();await page.locator('.live-context-panel').getByRole('button',{name:'打开战役战斗卡',exact:true}).click();
 check('host preparation opens canonical selector',await page.locator('[data-entry-source="runtime"]').isVisible());
 await sheet().locator('select').first().selectOption('actor3');check('selector converges to same state',await sheet().getByPlaceholder('护甲等级',{exact:true}).inputValue()==='18');await close();
 await page.locator('.live-context-panel').getByRole('button',{name:'打开战役战斗卡',exact:true}).click();await page.getByRole('button',{name:'添加怪物',exact:true}).click();await page.getByText('没有合适的怪物？',{exact:true}).click();await page.getByRole('button',{name:'创建自定义怪物',exact:true}).click();
 await sheet().getByPlaceholder('显示名称').fill('新地精');
 check('custom monster opens canonical editor before persistence',await page.evaluate(()=>window.iaFixture.actors.every(a=>a.displayName!=='新地精')));
 await sheet().getByPlaceholder('当前生命值',{exact:true}).fill('20');await sheet().getByPlaceholder('生命上限',{exact:true}).fill('20');await sheet().getByRole('button',{name:'创建角色',exact:true}).click();
 await sheet().getByPlaceholder('显示名称').waitFor();
 check('custom monster creation stays in canonical editor',await sheet().getByPlaceholder('显示名称').inputValue()==='新地精');
 const newId=await page.evaluate(()=>window.iaFixture.actors.at(-1).campaignActorInstanceId);
 check('monster creation uses canonical persistent object',await page.evaluate(()=>window.iaFixture.actors.at(-1).actorKind==='monster'));
 check('improvisation preserves table and runtime entry context',await page.locator('[data-live-play="host"]').count()===1&&await page.locator('[data-entry-source="runtime"]').isVisible());
 await close();await page.getByRole('button',{name:'放置 Token',exact:true}).click();
 const placement=page.locator('[data-canonical-surface="token-placement"]');
 check('one canonical placement form',await placement.locator('form').count()===1);
 const placementSignature=await placement.locator('form').innerText();
 await placement.getByText('新地精',{exact:true}).locator('..').locator('..').getByRole('button',{name:'放到地图',exact:true}).click();
 await page.waitForFunction(()=>window.iaFixture.writes.some(w=>w.kind==='map.append'));
 const placed=await page.evaluate(()=>window.iaFixture.writes.filter(w=>w.kind==='map.append').at(-1).body.payload.token);
 check('live placement preserves campaign actor linkage',placed.campaignActorId===newId&&placed.sourceActorInstanceId===newId);
 check('placement uses configured canonical actor HP seed',placed.hpSummary.current===20&&placed.hpSummary.max===20);
 await page.getByRole('button',{name:'战斗 / 裁定',exact:true}).click();await page.locator('.live-context-panel summary').filter({hasText:'设置'}).first().click();
 await page.locator('.live-context-panel').getByRole('button',{name:/＋ 新地精/}).click();
 await page.waitForFunction(()=>window.uxFixture.events.some(e=>e.kind==='combat.combatant_added'));
 check('enlisting preserves actor and placement relationship',await page.evaluate(id=>{const e=window.uxFixture.events.find(e=>e.kind==='combat.combatant_added');return e.payload.combatant.sourceActorInstanceId===id&&!!e.payload.combatant.mapTokenId;},newId));
 await shot('canonical-placement-combat-1440');
 await go('map-workspace&role=host');
 const workspacePlacement=page.locator('[data-canonical-surface="token-placement"]');
 check('workspace reuses identical marker form',await workspacePlacement.locator('form').innerText()===placementSignature);
 await workspacePlacement.getByRole('textbox',{name:'Token 名称'}).fill('机关');await workspacePlacement.getByRole('button',{name:'放到地图',exact:true}).first().click();
 const marker=await page.evaluate(()=>window.iaFixture.writes.at(-1).body.payload.token);
 check('manual marker does not create a persistent actor',marker.sourceType==='manual'&&!marker.campaignActorId);
 await go('workspace&readonly');await prep();await openActor(0);
 check('read-only entry has no enabled persistent edit',await page.getByRole('button',{name:'保存角色卡',exact:true}).isDisabled()&&await page.getByRole('button',{name:'清除战役覆写',exact:true}).isDisabled());
 await go('role=player');await page.getByRole('button',{name:'角色卡',exact:true}).click();const ownText=await page.locator('.live-context-content:visible').innerText();await page.keyboard.press('Escape');
 await page.locator('[data-map-token="t0"]').focus();await page.keyboard.press('Shift+Enter');await page.getByRole('button',{name:'打开已准入角色卡',exact:true}).click();
 check('own token opens same admitted sheet',await page.locator('.live-context-content:visible').innerText()===ownText);
 check('player never receives campaign editor',await sheet().count()===0);
 await shot('own-token-canonical-sheet-1440');await page.keyboard.press('Escape');await page.locator('[data-map-token="t3"]').focus();await page.keyboard.press('Shift+Enter');
 check('other token cannot open own source sheet',await page.getByRole('button',{name:'打开已准入角色卡',exact:true}).count()===0);
 await go('role=spectator');await page.locator('[data-map-token="t0"]').focus();await page.keyboard.press('Shift+Enter');
 check('spectator cannot open actor editor',await page.getByRole('button',{name:/打开.*角色卡|打开战役战斗卡/}).count()===0);
 await go('personal');const docButton=page.getByRole('button',{name:'打开文档',exact:true}).first();await docButton.click();const docTitle=await page.locator('h1').innerText();const docText=await page.locator('main').innerText();await page.getByRole('button',{name:'返回文档列表'}).click();
 check('personal document returns to its original hub',await page.getByRole('heading',{name:'我的内容',exact:true}).isVisible());
 await go('documents');await page.getByRole('button',{name:'本地用户（本人）',exact:true}).click();await page.getByText(docTitle,{exact:true}).click();
 check('document entrances reuse identical reader',await page.locator('main').innerText()===docText);
 await shot('canonical-document-reader-1440');
 await go('workspace&role=host&new');await page.getByPlaceholder('战役名称',{exact:true}).fill('新战役');await page.getByRole('button',{name:'创建',exact:true}).click();await page.getByText('新战役',{exact:true}).first().waitFor();await prep();
 await page.getByRole('button',{name:'创建 NPC',exact:true}).click();await sheet().getByPlaceholder('显示名称').fill('新角色');await sheet().getByRole('button',{name:'创建角色',exact:true}).click();await sheet().getByPlaceholder('显示名称').waitFor();await close();
 await page.getByText('高级：房间记录',{exact:true}).click();await page.getByRole('button',{name:'创建房间记录',exact:true}).click();await page.getByRole('button',{name:'开启联机大厅',exact:true}).click();await page.getByRole('button',{name:'以主持人身份进入桌面',exact:true}).click();await page.locator('[data-live-play="host"]').waitFor();
 check('new GM campaign actor room live workflow converges',await page.evaluate(()=>['campaign.create','actor.create','room.create','room.launch'].every(kind=>window.iaFixture.writes.some(w=>w.kind===kind))));
 await page.setViewportSize({width:1024,height:768});await page.getByRole('button',{name:'准备 / 管理',exact:true}).click();await page.locator('.live-context-panel').getByRole('button',{name:'打开战役战斗卡',exact:true}).click();
 await sheet().locator('select').first().selectOption({label:'新角色'});
 check('tablet editor includes editable fields',await sheet().getByPlaceholder('显示名称').inputValue()==='新角色');
 check('canonical dialog fits tablet width',await page.locator('[data-entry-source]').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;}));
 await shot('canonical-editor-1024');
 check('no browser exceptions',errors.length===0);
 const result={checks,passed:checks.length,screenshots,errors};await fs.writeFile(output+'/browser-results.json',JSON.stringify(result,null,2));await ctx.close();return result;
}
